apiVersion: apps/v1                           #version of api
kind: Deployment                              #mention kind as pod or service or replicaset or deployment etc
metadata:                                     #provide data
  name: webapp-page                           #name of the deployment
  labels:                                     #label information for services.yml
     app: webapp                              #name for recognizing pod
     
spec:                                         #specifications
  replicas: 2                                 #replicaset count, each replica will create 1 pod
  selector:                                   
    matchLabels:                              #for matching with deployment name
      app: webapp                             #name of the lable
  
  template:                                   #A Template to create container
    metadata:
      labels:
        apps: webapp
    spec:
       containers:
       - name: my-webapp
         image: kishore/webapp                #Name of the image in docker hub
         imagePullPolicy: Always
         ports:
         - containerPort: 8080
  strategy:                                   #Deployment strategy to make sure zerodowntime
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailabe: 1
