apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  labels: 
     app: php8.1-fpm-alpine

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: php8.1-fpm-alpine

  template:
    metadata:
      labels:
        app: php8.1-fpm-alpine
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
